<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.doctrine_entity_helper' shared service.

return $this->privates['maker.doctrine_entity_helper'] = new \Symfony\Bundle\MakerBundle\Doctrine\DoctrineEntityHelper(NULL);
