<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0b64f8l\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0b64f8l/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0b64f8l.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0b64f8l\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container0b64f8l\srcDevDebugProjectContainer(array(
    'container.build_hash' => '0b64f8l',
    'container.build_id' => '58b2811b',
    'container.build_time' => 1523479566,
));
